// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2koHzFlk229uEfvXLUXJVso1NpGszxSw',
    appId: '1:511252138434:web:b89a698083f5a432476e5b',
    messagingSenderId: '511252138434',
    projectId: 'feedchain-ca0d6',
    authDomain: 'feedchain-ca0d6.firebaseapp.com',
    storageBucket: 'feedchain-ca0d6.firebasestorage.app',
    measurementId: 'G-B6PGSG2V70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI4M_a94YOtgbdKNfZvqscozsHZq710Y8',
    appId: '1:511252138434:android:38f6b3a4199b10a4476e5b',
    messagingSenderId: '511252138434',
    projectId: 'feedchain-ca0d6',
    storageBucket: 'feedchain-ca0d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6tb94ZJg3-NtFbq3fbZpvR__-Jfng5zU',
    appId: '1:511252138434:ios:05dcc16ea999288b476e5b',
    messagingSenderId: '511252138434',
    projectId: 'feedchain-ca0d6',
    storageBucket: 'feedchain-ca0d6.firebasestorage.app',
    iosBundleId: 'com.example.feedchain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6tb94ZJg3-NtFbq3fbZpvR__-Jfng5zU',
    appId: '1:511252138434:ios:05dcc16ea999288b476e5b',
    messagingSenderId: '511252138434',
    projectId: 'feedchain-ca0d6',
    storageBucket: 'feedchain-ca0d6.firebasestorage.app',
    iosBundleId: 'com.example.feedchain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2koHzFlk229uEfvXLUXJVso1NpGszxSw',
    appId: '1:511252138434:web:3384ea958c60eeaf476e5b',
    messagingSenderId: '511252138434',
    projectId: 'feedchain-ca0d6',
    authDomain: 'feedchain-ca0d6.firebaseapp.com',
    storageBucket: 'feedchain-ca0d6.firebasestorage.app',
    measurementId: 'G-WD6BLQ6PVC',
  );

}